### ISSUE TITLE
Change appearance of website

### ISSUE THREAD

**Issue by cecilia-donnelly** [WorldWideTelescope/wwt-website#11]
The website group wants to make the existing website a little more intuitive to use.  To that end, we're in the process of creating a new layout.  See the image at the bottom of this issue for the current version.

This will be a "master issue" that points to other issues about specific
tasks.  Once the more specific issues are done, we can close this issue
as well.  I'm sure I'm missing some layout-related issues in this list.
As those come up, we'll open issues for them and link the new issues
here.

**Alter homepage according to new layout doc**
- replace the top-level menu
- remove video
- consolidate bottom news, twitter, and video boxes
- replace the footer menu(s) 

**Add pages**
- About
- Kiosk docs
- Rewrite FAQ
- Content creators
- "Take a Tour of  WWT"

**Consolidate and remove pages**
- Coming soon.

![wwt-website-draft-new-layout-no-comments](https://cloud.githubusercontent.com/assets/1497818/10797547/1cf10828-7d71-11e5-89f5-03d32a40d2d2.png)

**Comment by cecilia-donnelly** [comment]
@thewebkid, thoughts?  The layout above is certainly not a comprehensive list of website pages!  Please chime in if you have any concerns or ideas.

**Comment by mjbecker0** [comment]
Include link to WWT Ambassadors website please.

**Comment by cecilia-donnelly** [comment]
Hi, @mjbecker0.  Our goal is to include the content from the Ambassadors, Stories, and Workshops sites in the main site.  For now, where do you think would be a good place to link to the WWTA site?

**Comment by mjbecker0** [comment]
Hello Cecilia, 
I would change "contributing" to "helpful resources" or "more resources" and include a link to the Ambassadors site there. 
Thanks, Mary Becker

**Comment by philrosenfield** [comment]
cleaning up old issues -- if needs are not met with re-tooled website please reopen, or open a new issue
