### ISSUE TITLE
Redis high error rate

### ISSUE THREAD

**Issue by coderandhiker** [WorldWideTelescope/wwt-website#221]
We are seeing a high incidence of error with the Redis instance.  It looks like there is a dependency taken 4 minor revisions behind for the StackExchange.Redis library that is resulting in thread pool exhaustion errors being reported.  

See https://github.com/StackExchange/StackExchange.Redis/issues/1545#issuecomment-674325369

**Comment by coderandhiker** [comment]
@twsouthwick - you pushed an update, I will keep an eye on the problem over the coming 48 hours and see whether it is resolved.

**Comment by pkgw** [comment]
GitHub auto-closed this but I think we should keep it open until the numbers bear it out.

**Comment by pkgw** [comment]
OK, I think we can say this is dealt with.
