### ISSUE TITLE
WWT Webservice discovery endpoint is broken

### ISSUE THREAD

**Issue by coderandhiker** [WorldWideTelescope/wwt-website#224]
See: expected result from production: http://worldwidetelescope.org/webservices/wwtwebservice.asmx?disco

and the actual result from AppService: http://wwtcoreapp-app-service.azurewebsites.net/webservices/wwtwebservice.asmx?disco

@twsouthwick  is this just a routing issue?

[InvalidOperationException: The view '~/Views/webservices/wwtwebservice.asmx.cshtml' or its master was not found or no view engine supports the searched locations. The following locations were searched:
~/Views/webservices/wwtwebservice.asmx.cshtml]
   System.Web.Mvc.ViewResult.FindView(ControllerContext context) +511
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +143
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +91
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +795
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) +188
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +43
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +651
   System.Web.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0() +40
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +155
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +134

**Comment by pkgw** [comment]
FWIW, I added these URLs to the database to make sure that they are written down, but I would be *extremely* surprised if they were ever used in practice.

**Comment by twsouthwick** [comment]
I don't see it in the repo. We'll have to check the VM to see if it's still there

**Comment by pkgw** [comment]
@twsouthwick The live VMs do have a file `WebServices/WWTWebService.asmx`. I don't understand exactly how it works, but it's literally one line:

```
<%@ WebService Language="C#" CodeBehind="~/App_Code/WWTWebService.cs" Class="WebServices.WWTWebService" %>
```

**Comment by twsouthwick** [comment]
That's it! The code for it is in the wwtweb services project.
