### ISSUE TITLE
[Same behavior] Catalog service throws a 500 when bad inputs are supplied

### ISSUE THREAD

**Issue by coderandhiker** [WorldWideTelescope/wwt-website#225]
App Service: http://wwtcoreapp-app-service.azurewebsites.net/wwtweb/catalog.aspx?W=UvevffFcbgyvtug
Classic VMs: http://wwt-web01.cloudapp.net/wwtweb/catalog.aspx?W=UvevffFcbgyvtug

Results in a 500, I would expect a 404 would be more appropriate here.

@pkgw this behavior is the same in the new version as it was in the old version

**Comment by pkgw** [comment]
For this one, I'm confident that changing the behavior to return 404s instead of 500s will be safe to do.

**Comment by twsouthwick** [comment]
Fixed by #219
