### ISSUE TITLE
[Regression] Thumbnail is failing with a Null Reference Exception in some cases

### ISSUE THREAD

**Issue by coderandhiker** [WorldWideTelescope/wwt-website#228]
For reference: 

http://wwtcoreapp-app-service.azurewebsites.net/wwtweb/thumbnail.aspx?Name=tyvzaddge

http://wwt-web01.cloudapp.net/wwtweb/thumbnail.aspx?Name=tyvzaddge

![image](https://user-images.githubusercontent.com/25612130/100009243-74e40b80-2d83-11eb-94b0-bad7ed6c59d9.png)

@twsouthwick, @pkgw - I didn't work on this part of the data migration so I am not familiar, is it possible we missed some source data when we brought over thumbnails?

**Comment by pkgw** [comment]
There is a default thumbnail that gets served up if the requested name isn't available — looks like that fallback is failing in the new app service.
