### ISSUE TITLE
Styles missing on certain pages

### ISSUE THREAD

**Issue by cecilia-donnelly** [WorldWideTelescope/wwt-website#23]
A user reports:

> FYI, several of the “technical” WWT pages come up looking white & with missing images when you google search for them.  For example:  http://www.worldwidetelescope.org/docs/worldwidetelescopeprojectionreference.html

It looks like no stylesheets are being associated with the referenced page.  I'll look into this and see if I can find out why this is happening.

**Comment by philrosenfield** [comment]
This should now be obsolete since we've moved technical page content to github
