### ISSUE TITLE
Add content to homepage

### ISSUE THREAD

**Issue by cecilia-donnelly** [WorldWideTelescope/wwt-website#24]
@sarahb55 requests some new content on the homepage (and one other change):
1. Add WWT Stories and WWT Ambassadors items to the carousel.
2. I am hoping you can also embed/add links to the two movies as a slide or on the home page perhaps as other callouts like the three below the slide deck? http://youtu.be/_FMmOjjlI8o and http://youtu.be/d36Ix0uQ1hg
3. Remove the "Educator Resources" section from [the Educators page](http://www.worldwidetelescope.org/Educators/WWTA]).

**Comment by cecilia-donnelly** [comment]
The proposed slides:

![ambassaorsslide](https://cloud.githubusercontent.com/assets/1497818/11509091/babbe68e-9821-11e5-891c-4fc3687e5021.png)
![wwtstoriesslide](https://cloud.githubusercontent.com/assets/1497818/11509092/bacfd32e-9821-11e5-9216-b1a063785851.png)

**Comment by mjbecker0** [comment]
Thank you Cecilia !
--------------------------------------------
On Tue, 12/1/15, Cecilia Donnelly <notifications@github.com> wrote:

 Subject: [wwt-website] Add content to homepage (#24)
 To: "WorldWideTelescope/wwt-website" <wwt-website@noreply.github.com>
 Date: Tuesday, December 1, 2015, 12:49 PM
 
 @sarahb55 requests
 some new content on the homepage (and one other change):
 
 
 Add WWT Stories and WWT Ambassadors items to the
 carousel.
 I am hoping you can also embed/add links to the two
 movies as a slide or on the home page perhaps as other
 callouts like the three below the slide deck? http://youtu.be/_FMmOjjlI8o
 and http://youtu.be/d36Ix0uQ1hg
 
 Remove the "Educator Resources" section from
 the
 Educators page.
 
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by philrosenfield** [comment]
[cleaning up old issues]
