### ISSUE TITLE
WWT's Wikipedia page needs updating, and will need regular maintenance.

### ISSUE THREAD

**Issue by kfogel** [WorldWideTelescope/wwt-website#25]
We should bring https://en.wikipedia.org/wiki/WorldWide_Telescope up to date.  I did a [band-aid fix to the introduction](https://en.wikipedia.org/w/index.php?title=WorldWide_Telescope&type=revision&diff=693622623&oldid=690876990) today, but really the whole page needs a once-over, and perhaps regularly scheduled maintenance once we have the resources for that.

**Comment by aagoodman** [comment]
Seems to have been updated by Doug Roberts July 2016.
