### ISSUE TITLE
Add Processing Panoramas to Learn/Expore

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#27]
We need to add a section to "Learn/Explore/Processing Panoramas."  The text is in the Word doc below and the images are in as well and separately below.

[Processing Panoramas - Documentation.docx](https://github.com/WorldWideTelescope/wwt-website/files/125782/Processing.Panoramas.-.Documentation.docx)
![spheretoaster1](https://cloud.githubusercontent.com/assets/9676722/12967829/adec5a1a-d02f-11e5-9183-266d27b603f8.jpg)
![spheretoaster2](https://cloud.githubusercontent.com/assets/9676722/12967830/adec5dd0-d02f-11e5-8b38-e9aaffe1001f.jpg)
![spheretoaster3](https://cloud.githubusercontent.com/assets/9676722/12967828/adec3a4e-d02f-11e5-98e9-957b082eb8fd.jpg)
![irfanview1](https://cloud.githubusercontent.com/assets/9676722/12967831/adecb7c6-d02f-11e5-97c7-7e484d9a4e87.jpg)
![irfanview2](https://cloud.githubusercontent.com/assets/9676722/12967832/adee49ce-d02f-11e5-8a08-1c7811e427a8.jpg)

**Comment by thewebkid** [comment]
Ok, I have staged this: http://wwtstaging.azurewebsites.net/

Couple of notes. 
Link to the formatted sphere toast docs (http://worldwidetelescope.org/Developers/DataToolsGuide#WWTSphereToaster) not the plain html src file.
I need a youtube link for the tutorial :)

I did not deeply proof this. A couple of tweaks and general formatting to get this published.

Let me know when you approve and I will deploy live...

**Comment by doctorspaceman** [comment]
Thanks Ron.  I updated the documents (see the files below).  There are many small changes so it would probably be easier for you to replace completely rather than track the changes.  Note, I am also putting in another issue (#28) for the Explore/Processing All-Sky Images which is very similar.  

Note, in the document I had captions for the images.  That was just for you to know the file name for each image in case you wanted those instead of cutting them out of the Word document.  Don't put the figure captions into the website.

![irfanview2](https://cloud.githubusercontent.com/assets/9676722/12994434/47e241fa-d0e6-11e5-9633-dd3c4e496021.jpg)
[Processing Panoramas - Documentation.docx](https://github.com/WorldWideTelescope/wwt-website/files/127270/Processing.Panoramas.-.Documentation.docx)
![spheretoaster1](https://cloud.githubusercontent.com/assets/9676722/12994436/47e2abcc-d0e6-11e5-99fb-526a68b2085f.jpg)
![spheretoaster2](https://cloud.githubusercontent.com/assets/9676722/12994435/47e26a18-d0e6-11e5-9729-a63697c8ef6f.jpg)
![spheretoaster3](https://cloud.githubusercontent.com/assets/9676722/12994437/47e3e640-d0e6-11e5-9542-bfe5a5830fd9.jpg)

**Comment by thewebkid** [comment]
ok, I have staged the new one. Please take a look.

**Comment by doctorspaceman** [comment]
Looks good.
