### ISSUE TITLE
Add Processing All-Sky Images to Learn/Expore

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#28]
This is a similar documentation addition similar to the panorama one (#27). This would be Explore/Processing All-Sky Images.  Below are the files.

[Processing All-Sky Images - Documentation.docx](https://github.com/WorldWideTelescope/wwt-website/files/127276/Processing.All-Sky.Images.-.Documentation.docx)

![spheretoastersky1](https://cloud.githubusercontent.com/assets/9676722/12994470/9384419e-d0e6-11e5-804e-321bfd1514f4.jpg)
![spheretoastersky2](https://cloud.githubusercontent.com/assets/9676722/12994471/93855a0c-d0e6-11e5-8886-9427016d9409.jpg)
![spheretoastersky3](https://cloud.githubusercontent.com/assets/9676722/12994472/93863fd0-d0e6-11e5-81e0-0d5039bcaad7.jpg)
![spheretoastersky4](https://cloud.githubusercontent.com/assets/9676722/12994469/93838470-d0e6-11e5-9bd4-c157c2e06c1d.jpg)

**Comment by thewebkid** [comment]
ok, this is staged. Can you take a look and see if you need any edits?

**Comment by doctorspaceman** [comment]
This looks good to me
