### ISSUE TITLE
404 Error on some of the Dev Documentation

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#29]
On page: http://worldwidetelescope.org/Developers/DataToolsGuide

All of these get 404:
• WorldWide Telescope Authoring
• WorldWide Telescope Data Files Reference
• WorldWide Telescope Localization Tool
• WorldWide Telescope Projection Reference
• WorldWide Telescope Web Control Script Reference

From <http://worldwidetelescope.org/Developers/DataToolsGuide>

**Comment by thewebkid** [comment]
Ok, I have staged a fix. Removed the loc tool - I think that got cut a while back.
