### ISSUE TITLE
Clarify "Users" vs "Customizers" vs "Developers".

### ISSUE THREAD

**Issue by kfogel** [WorldWideTelescope/wwt-website#3]
http://worldwidetelescope.org/Developers/ is really aimed at a certain kind of power user -- a user who customizes WWT.  The content on that page is not about  developing WWT in the sense of contributing to the code in the GitHub repositories.

We'll need to make our language around these different roles consistent, and then make the page structure and content line up with that language.  In the meantime, there isn't really a "developers central" type of page anywhere on the main site (as far as I can see).  We may want to just have a short jumping-off page that points people to dev documentation in the wiki or something like that, since the wiki will be easier for developers to contribute to anyway.

The real developers area, wherever it lives, would have guidelines like our conventions on labels and milestones (see [this mail](https://groups.google.com/d/msg/wwt-aas-task-force/YQgh7519cMU/qFrKuvdZBwAJ), for example), coding conventions, etc.

Anyway, for the moment I'm just filing this ticket so we don't forget about this problem.

**Comment by kfogel** [comment]
See also https://github.com/WorldWideTelescope/wwt-windows-client/pull/25, where user @bluephoton indicates that such a guide would be useful.

**Comment by philrosenfield** [comment]
I believe the re-tooling of the website has accomplished this. Please reopen if you feel otherwise.
