### ISSUE TITLE
Planet 9 News article (and Carousel hero)

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#30]
We need a new hero for Planet 9 which points back to someplace we can keep news items like this.  There is a pulse of interest but we want to put assets for reuse in a place that doesn't change location for the long run.  

Here is the Word Doc that has the information and the hero image separately.  The Word file has links to the animation video and layer file that was used to create it.  They should be copied to blob storage and links put into the webpage to get them from there.

![planet9-hero](https://cloud.githubusercontent.com/assets/9676722/12996674/9264f1e4-d0f7-11e5-86b1-23c0cd3e2a12.jpg)
[Planet 9 - Text.docx](https://github.com/WorldWideTelescope/wwt-website/files/127386/Planet.9.-.Text.docx)

**Comment by thewebkid** [comment]
I've staged the hero and a new section - news. Thinking is that we put open source, aas, planet 9, etc in there and link to each article. It might make things crisper if we put dates on each story too. Thoughts?

Just an initial idea. Let me know how you like it and I can deploy once you are satisfied with everything

http://wwtstaging.azurewebsites.net/

**Comment by doctorspaceman** [comment]
This looks good for a news section.  I'll get you the AAS news story and maybe the Gravity Wave one too.
