### ISSUE TITLE
Add "Making Video Abstracts" to Learn/Authoring

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#32]
Please add this documentation under Learn/Authoring

[Making Video Abstracts.docx](https://github.com/WorldWideTelescope/wwt-website/files/267127/Making.Video.Abstracts.docx)

**Comment by thewebkid** [comment]
Added this. Please proof 
http://wwtstaging.azurewebsites.net/Learn/Authoring#videoabstracts
