### ISSUE TITLE
Add "Adding Satellite and Minor Planet Orbits" to "Learn/Authoring"

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#34]
[Adding Satellite and Minor Planet Orbits - NEW.zip](https://github.com/WorldWideTelescope/wwt-website/files/267135/Adding.Satellite.and.Minor.Planet.Orbits.-.NEW.zip)

**Comment by thewebkid** [comment]
I have staged this here:
http://wwtstaging.azurewebsites.net/Learn/Exploring#AddingMinorPlanetOrbits

I will knock out the other two next and deploy when you give the nod

**Comment by thewebkid** [comment]
Oops, now I see in the title that it goes under authoring. Moved to 
http://wwtstaging.azurewebsites.net/Learn/Authoring#AddingMinorPlanetOrbits
