### ISSUE TITLE
Eclipse News Page

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#36]
We need to add a new news story added to the web page? We don't need it as the highlighted  now but  just want to have the story as a page that can grow and be linked to. When it gets closer next year we will push it hard.

[Eclipse 2017.zip](https://github.com/WorldWideTelescope/wwt-website/files/315354/Eclipse.2017.zip)

**Comment by thewebkid** [comment]
http://worldwidetelescope.org/news/eclipse2017

Done :)

**Comment by doctorspaceman** [comment]
Looks great!  Thanks!

-Doug

On 6/14/2016 10:02 PM, thewebkid wrote:
>
> http://worldwidetelescope.org/news/eclipse2017
>
> Done :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/WorldWideTelescope/wwt-website/issues/36#issuecomment-226088593>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AJOnsvAzYKbzxcKarrfFSAKrdWt8S3qRks5qL4d9gaJpZM4I18mX>.
>


-- 
Doug Roberts
WorldWide Telescope Project Director
American Astronomical Society
2000 Florida Ave NW, Suite 300
Washington, DC 20009
202.328.2010 ext 112 | doug.roberts@aas.org

**Comment by erinjohn** [comment]
This is great!  We've been talking about next year's eclipse as part of our
Moon Phases and Eclipses lessons to hundreds of Middle School students.
Thanks for the video version of the visualization in WWT!

--Erin

**Comment by doctorspaceman** [comment]
Erin.  Thanks.  If you want to make anything new to add of have ideas we can put them here.  I was thinking about an extensive tutorial about making a tour simulating what it will look like from a specific location and to compare the difference between total and partial eclipses to encourage people to drive the miles necessary to see totality.
