### ISSUE TITLE
New 5.5 download page

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#41]
[Download 5.5.docx](https://github.com/WorldWideTelescope/wwt-website/files/354741/Download.5.5.docx)

**Comment by mjbecker0** [comment]
Yes!!! So many people ask if it runs on Windows 10. Thank you

**Comment by thewebkid** [comment]
It works in 10 and the updated text and build is there now :)

http://worldwidetelescope.org/Download/
