### ISSUE TITLE
New documentation supporting release of WebGL Web Client

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#44]
* Web-based Tour Authoring 
   * [Put this at top of authoring documentation – and make it available at the following URL: http://www.worldwidetelescope.org/Learn/Authoring#webauthoring]
   * [Web-based Tour Authoring - NEW.zip](https://github.com/WorldWideTelescope/wwt-website/files/460521/Web-based.Tour.Authoring.-.NEW.zip)

* What's New
   * [What's New.zip](https://github.com/WorldWideTelescope/wwt-website/files/460544/What.s.New.zip)
   * [This needs to go on top of the What’s New page at: http://www.worldwidetelescope.org/Learn/WhatsNew keeping the 5.1 & 5.0 sections]

**Comment by thewebkid** [comment]
Ok, starting this now. Will get it staged soon.

**Comment by thewebkid** [comment]
Done and staged. I will push this live tonight after the other docs.
