### ISSUE TITLE
New News Items

### ISSUE THREAD

**Issue by doctorspaceman** [WorldWideTelescope/wwt-website#45]
[New News Items 9-7-16.zip](https://github.com/WorldWideTelescope/wwt-website/files/460736/New.News.Items.9-7-16.zip)

For now these should be placed:
* 2016 WWT Prize News.docx - http://www.worldwidetelescope.org/news/2016wwtprize 
* WWT On-line Training News.docx - http://www.worldwidetelescope.org/news/onlinetraining
 
Later we will want to put the prize as the first stop on the carousel on the home page.  But I don't have any good graphics now.

**Comment by thewebkid** [comment]
I am starting this now. I don't see any jpgs or pngs in the zip. I will extract from the word doc unless you can upload them now...

**Comment by thewebkid** [comment]
Ok, these are staged. I will go ahead and put on live site...

**Comment by thewebkid** [comment]
Ok, they are live. FYI, I had to create all but the contest submission graphic by hand due to the compression Word uses on images. Don't forget the images next time if you have them :)
