### ISSUE TITLE
Broken Links: DataFilesReference page 17

### ISSUE THREAD

**Issue by KingArthur10** [WorldWideTelescope/wwt-website#46]
All the links for the WTML Samples are broken
http://worldwidetelescope.org/Developers/DataFilesReference

**Comment by KingArthur10** [comment]
Should probably scrape the site for broken links to get an idea on how many are broken and where.  Maybe this exists but I didn't see anything.

**Comment by philrosenfield** [comment]
Fixed.

Thanks, and I did end up scraping the site when porting the documentation to github. The meta-repo is here: https://github.com/WorldWideTelescope/wwt-documentation
