### ISSUE TITLE
Broken Images: DataFilesReference pages have broken images

### ISSUE THREAD

**Issue by KingArthur10** [WorldWideTelescope/wwt-website#47]
Broken images on pg 5, 18, 19-22

**Comment by philrosenfield** [comment]
Fixed. 

FYI: We have ported this guide here: https://github.com/WorldWideTelescope/worldwide-telescope-data-files-reference 

Which is rendered here: https://worldwidetelescope.gitbooks.io/worldwide-telescope-data-files-reference/content/
