### ISSUE TITLE
Arrow icons should disappear when on the last page of a list of pages

### ISSUE THREAD

**Issue by KingArthur10** [WorldWideTelescope/wwt-website#48]
Go to DataFIlesReference page http://worldwidetelescope.org/Developers/DataFilesReference

Click the >> button to go to the last page.  Notice that the arrow buttons are still there.  Since you're on the last page, should not have arrow buttons as a visual indicator that you're on the last page.

**Comment by philrosenfield** [comment]
[obsolete now that we are using gitbooks and markdown]
