### ISSUE TITLE
Feature Request: Communities: Include license information for shared content

### ISSUE THREAD

**Issue by KingArthur10** [WorldWideTelescope/wwt-website#49]
It's unclear what the license is on the various community shared objects, and I don't see any clear indicator whether items uploaded to the community area are under a creative commons license or individual licenses.

A lot of institutions, especially planetariums, require some license to be able to determine if they can use the content in a dome or as part of a larger program/fulldome video.  Would be great to have this clearly indicated and/or give the uploader the requirement to specify the license under which the content is usable.

**Comment by pkgw** [comment]
This issue remains valid but the broader future of the Communities service needs to be planned out before anything is going to happen here.
