### ISSUE TITLE
AVM tagging - how?

### ISSUE THREAD

**Issue by nicocarver** [WorldWideTelescope/wwt-website#54]
I am interested in embedding [my images](https://www.flickr.com/photos/2ghouls) in to the WorldWideTelescope, and then embedding my image plus the WWT Web Control on my personal website. My understanding from the [embed page on the website](http://www.worldwidetelescope.org/Use/Embed) is they need to be AVM-tagged for this to work. You provide a link to the [VAMP website](https://www.virtualastronomy.org/avm_metadata.php), which does explain the AVM standard and provides methods for tagging, but none of those methods are currently operational (avm tagging tool is a broken link, Adobe Metadata panels don't work with any modern versions of Photoshop/Bridge).  Is there an up-to-date method for AVM tagging that you could link to or explain on the website?  Many thanks!

**Comment by augustfly** [comment]
@nicocarver you could try: https://github.com/astrofrog/pyavm

**Comment by pkgw** [comment]
We should provide a tutorial about this, but this repo's focus is moving to be squarely the place for the backend data services, so I'm going to close this issue. @nicocarver you might check out https://embed.worldwidetelescope.org/ for a sneak preview ... astrometry.net might be your best bet.
