### ISSUE TITLE
Midi controller documentation link returns 404

### ISSUE THREAD

**Issue by apiszcz** [WorldWideTelescope/wwt-website#57]
The link in this manual description of where to retrieve the controller mapping file appears to be incorrect? Is there a valid Numark DJ2Go controller mapping file URL? Thank you.

http://cdn.worldwidetelescope.org/Content/Learn/Numark%20DJ2Go.wwtmm

MIDI Controller
Any MIDI controller can be used to control WorldWide Telescope. You can re-use mapping of WWT functions created by someone else. You can also create your own or edit a previously-created mapping. Start by selecting “Settings/Controller Setup...” This brings up a dialog window where you can select a file containing the mapping functions. For the Numark DJ2Go you can download a standard mapping file.

**Comment by pkgw** [comment]
It looks like the correct link is this:

http://wwtweb.blob.core.windows.net/learn/Numark%20DJ2Go.wwtmm

I'll fill a pull request to fix the website.
