### ISSUE TITLE
Forum links out of date

### ISSUE THREAD

**Issue by MrGrymReaper** [WorldWideTelescope/wwt-website#59]
Following an email with a staff member who suggested posting on the forum, I noticed the website link was out of date again.

The host name linked to was http://forums.worldwidetelescope.org/ when it should be instead linking to https://wwt-forum.org. This was noticed on the URL address for Support, Issues and Bugs page available at http://www.worldwidetelescope.org/Support/IssuesAndBugs.

Please update the link so it goes to the current forums address.

**Comment by pkgw** [comment]
Thanks! This should be updated, but also it's a reminder that I should update the `forums` subdomain to redirect to the current incarnation.

**Comment by pkgw** [comment]
I implemented this.
