### ISSUE TITLE
OAuth login workflow stopped working

### ISSUE THREAD

**Issue by calluna** [WorldWideTelescope/wwt-website#97]
When clicking on "sign in" in the top right corner it has me sign into my Microsoft account. Then when I sign in it goes to a WWT web 404 page. When I then go back to the main WWT web client page I am not signed in anymore.

![Screen Shot 2020-09-24 at 3 28 03 PM](https://user-images.githubusercontent.com/844214/94206791-1ed61300-fe7b-11ea-9d8f-1228b1c5dd82.png)

**Comment by pkgw** [comment]
Technical notes: root symptom is a 404 error for `/LiveId/AuthenticateFromCode/{code}` but I believe that the underlying issue is that the necessary OAuth cookies aren't being passed to that API call.

**Comment by pkgw** [comment]
This should now be fixed!
